### ISSUE TITLE
Cannot read properties of undefined (reading 'filter')

### ISSUE THREAD

**Issue by Joolio12** [tloncorp/tlon-apps#3406]
Error with %groups, 
Urbit Kernel Version (b4l49)
Urbit Runtime Version 3.0
```
TypeError: Cannot read properties of undefined (reading 'filter')
    at https://btc.urbitstars.org/apps/groups/assets/index.52dc4675.js:36:50587
    at Object.Jd [as useMemo] (https://btc.urbitstars.org/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:57586)
    at f.useMemo (https://btc.urbitstars.org/apps/groups/assets/@tlon/sigil-js.4fa95bd4.js:12:5789)
    at Ia (https://btc.urbitstars.org/apps/groups/assets/index.52dc4675.js:36:50573)
    at Kn (https://btc.urbitstars.org/apps/groups/assets/index.52dc4675.js:44:19742)
    at rm (https://btc.urbitstars.org/apps/groups/assets/index.52dc4675.js:48:265477)
    at Kl (https://btc.urbitstars.org/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:52884)
    at Ka (https://btc.urbitstars.org/apps/groups/assets/react-beautiful-dnd.fde4d763.js:19:62361)
    at mf (https://btc.urbitstars.org/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:9604)
    at pf (https://btc.urbitstars.org/apps/groups/assets/react-beautiful-dnd.fde4d763.js:23:947)
```

**Comment by Joolio12** [comment]
no longer reproducible, you may close ticket

**Comment by Joolio12** [comment]
It appears to be working now, but I will try to reproduce.  There was a notice of something "updating in the background" although the message disappeared after a few seconds.
